import { Shield, Lock, Eye, Globe, Database, Scale } from 'lucide-react';

export default function PrivacyPolicy() {
  const sections = [
    {
      title: "1. Data Sovereignty & Ownership",
      content: "All data ingested into the Sovereign Matrix, including source code, project metadata, and agent directives, remains the sole intellectual property of the User. Realms 2 Riches does not claim ownership over any output generated by the swarm."
    },
    {
      title: "2. Sharded Memory Isolation",
      content: "Our RAG (Retrieval-Augmented Generation) systems utilize cryptographic sharding to ensure that knowledge ingested by one Sovereign Realm is never accessible to another. Your competitive advantages are mathematically secured."
    },
    {
      title: "3. API Key & Environment Security",
      content: "Environment variables, specifically API keys for LLMs, social platforms, and payment gateways, are stored in memory only or encrypted at rest using AES-256. These keys are never transmitted outside of the specific tool invocation lifecycle."
    },
    {
      title: "4. Telemetry & Neural Logging",
      content: "We collect high-level telemetry (throughput, token usage, error rates) to maintain matrix stability. Detailed agent reasoning logs are stored locally within your containerized instance and are not uploaded to our central servers."
    },
    {
      title: "5. Third-Party Data Transmission",
      content: "Directives involving external tools (e.g., posting to LinkedIn, processing Stripe payments) transmit only the minimum required data packets. We do not use your private data to train global baseline models."
    },
    {
      title: "6. Zero-Trust Access",
      content: "Access to the Founder Dashboard and Agent Cockpit is controlled via your Sovereign License Key. Unauthorized attempts to uplink to the Matrix are blocked via our Ed25519 cryptographic gate."
    }
  ];

  return (
    <div className="max-w-5xl mx-auto py-20 px-4 font-mono text-white">
      <div className="text-center mb-20 border-b border-primary/20 pb-12">
        <Lock className="text-primary mx-auto mb-6" size={48} />
        <h1 className="text-6xl font-black tracking-tighter uppercase italic">Privacy <span className="text-primary">Protocol</span></h1>
        <p className="text-gray-500 text-xs mt-4 uppercase tracking-[0.4em]">Secure Data Governance v3.9.1</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {sections.map((s, i) => (
          <div key={i} className="bg-black/40 p-10 rounded-[2rem] border border-white/5 hover:border-primary/20 transition-all group">
            <h3 className="text-white font-black mb-4 uppercase tracking-tight flex items-center gap-3">
              <span className="text-primary opacity-50 group-hover:opacity-100 transition-opacity">0{i+1}</span>
              {s.title}
            </h3>
            <p className="text-gray-400 text-sm leading-relaxed font-light">{s.content}</p>
          </div>
        ))}
      </div>

      <div className="mt-20 p-12 bg-primary/5 rounded-[3rem] border border-primary/10 text-center relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(0,255,136,0.05),transparent)]" />
        <p className="text-gray-500 text-xs uppercase tracking-widest mb-6 relative z-10">Questions regarding matrix sovereignty?</p>
        <a href="mailto:security@realms2riches.ai" className="text-primary font-black text-xl hover:underline relative z-10">security@realms2riches.ai</a>
      </div>
    </div>
  );
}
