import { Gavel, ShieldAlert, Zap, Globe, Cpu, Scale } from 'lucide-react';

export default function TermsOfService() {
  const terms = [
    {
      title: "1. Autonomous Agent Liability",
      content: "Realms 2 Riches provides access to a 1000-agent swarm. By initiating an ignition sequence, the User acknowledges that agents operate autonomously. Realms 2 Riches is not liable for code errors, business decisions, or financial outcomes resulting from agentic directives."
    },
    {
      title: "2. License & Subscription Matrix",
      content: "Access is granted on a per-license basis. Subscriptions are billed monthly via Stripe. Sovereign Realms are subject to immediate suspension if license verification fails or if the cryptographic signature is tampered with."
    },
    {
      title: "3. Prohibited Operations",
      content: "Users are strictly prohibited from using the Sovereign Swarm for: (a) Developing malware or cyber-weapons; (b) Conducting disinformation campaigns; (c) Violating social platform terms of service; (d) Attempting to reverse-engineer the Orchestrator logic."
    },
    {
      title: "4. Resource Allocation & Scaling",
      content: "While our swarm is theoretically infinite, physical compute limits apply. Realms 2 Riches reserves the right to throttle agent throughput during periods of matrix-wide high latency to ensure core stability."
    },
    {
      title: "5. Intellectual Assets",
      content: "All source code, documentation, and marketing assets generated by the agents are 'Work Made for Hire' and belong exclusively to the User. The User is responsible for verifying the legal uniqueness of all generated artifacts."
    },
    {
      title: "6. Termination of Neural Link",
      content: "Realms 2 Riches may terminate a User's Neural Link (access) at any time for violation of these protocols. Upon termination, local data remains with the user, but access to the 1000-agent specialized fleet is severed."
    }
  ];

  return (
    <div className="max-w-5xl mx-auto py-20 px-4 font-mono text-white">
      <div className="text-center mb-20 border-b border-primary/20 pb-12">
        <Scale className="text-primary mx-auto mb-6" size={48} />
        <h1 className="text-6xl font-black tracking-tighter uppercase italic">Terms of <span className="text-primary">Engagement</span></h1>
        <p className="text-gray-500 text-xs mt-4 uppercase tracking-[0.4em]">Sovereign Operating Protocol v3.9.1</p>
      </div>

      <div className="space-y-12">
        {terms.map((t, i) => (
          <div key={i} className="bg-black border border-white/10 p-12 rounded-[2.5rem] group hover:border-primary/30 transition-all relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-primary opacity-20 group-hover:opacity-100 transition-opacity" />
            <h3 className="text-primary font-black mb-6 uppercase text-2xl flex items-center gap-4">
              <span className="text-gray-800 font-mono">0{i+1}</span>
              {t.title}
            </h3>
            <p className="text-gray-400 text-base leading-relaxed font-light">{t.content}</p>
          </div>
        ))}
      </div>

      <div className="mt-24 text-[10px] text-gray-600 uppercase tracking-[0.5em] text-center max-w-2xl mx-auto leading-loose">
        BY PROCEEDING WITH THE SOVEREIGN IGNITION COMMAND (.\SOVEREIGN_START.ps1), YOU FORMALLY ACKNOWLEDGE AND ACCEPT THE NEURAL LINK PROTOCOLS DEFINED ABOVE.
      </div>
    </div>
  );
}
