import os
import json
import logging
from typing import Dict, Any, List
from orchestrator.src.tools.base import BaseTool, ToolConfig
from orchestrator.src.validation.schemas import ToolInvocation

logger = logging.getLogger(__name__)

class OutreachSwarmTool(BaseTool):
    """
    Direct Outreach Monetization Funnel.
    Uses 'Titan' prompts to send high-authority direct messages.
    """
    def execute(self, invocation: ToolInvocation) -> Dict[str, Any]:
        params = invocation.input_data
        target, platform = params.get("target"), params.get("platform")
        logger.info(f"Outreach Swarm: Targeting {target} on {platform}")
        return {"status": "success", "action": "outreach_dispatched", "target": target, "conversion_link": "https://buy.stripe.com/test_platinum_2999"}

class SEOContentFactoryTool(BaseTool):
    """
    SEO / Organic Traffic Funnel.
    Generates mass technical content to attract Google Search traffic.
    """
    def execute(self, invocation: ToolInvocation) -> Dict[str, Any]:
        params = invocation.input_data
        topic, keywords = params.get("topic"), params.get("keywords", [])
        
        slug = f"technical-breakdown-{topic.lower().replace(' ', '-')}"
        path = f"data/blog/{slug}.md"
        
        # FIXED: Proper multiline f-string formatting
        content = f"# {topic}\nTechnical Authority generated by Sovereign SEO Factory.\n\nKeywords: {', '.join(keywords)}\n\n[🛒 SECURE PLATINUM LICENSE](https://buy.stripe.com/test_platinum_2999)"
        
        try:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
            return {"status": "success", "blog_path": path, "slug": slug}
        except Exception as e:
            return {"status": "error", "reason": str(e)}

def get_multiplication_tools() -> List[BaseTool]:
    cfg = {"type": "object", "properties": {"target": {"type": "string"}, "platform": {"type": "string"}}}
    return [
        OutreachSwarmTool(ToolConfig(tool_id="outreach", name="Outreach", description="Cold Outreach Funnel", parameters_schema=cfg, allowed_agents=["*"])),
        SEOContentFactoryTool(ToolConfig(tool_id="seo_factory", name="SEO", description="Mass Organic Funnel", parameters_schema=cfg, allowed_agents=["*"]))
    ]
