import os
import json
import logging
from typing import Dict, Any, List
from orchestrator.src.tools.base import BaseTool, ToolConfig
from orchestrator.src.validation.schemas import ToolInvocation
from orchestrator.src.core.config import settings

logger = logging.getLogger(__name__)

class OutreachSwarmTool(BaseTool):
    """
    Direct Outreach Monetization Funnel.
    Uses 'Titan' prompts to send high-authority cold emails.
    """
    def execute(self, invocation: ToolInvocation) -> Dict[str, Any]:
        params = invocation.input_data
        target_email = params.get("target_email")
        target_name = params.get("target_name", "Entrepreneur")
        
        logger.info(f"Outreach Swarm: Targeting {target_email}")
        
        conversion_link = "https://buy.stripe.com/5kQcN5aHLdIdbAS4dd8so02" # Jarvis Premium
        
        subject = "Autonomous Revenue Operations for your Team"
        body = (
            f"Hi {target_name},\n\n"
            f"I noticed your great work and wanted to connect. "
            f"At Realms2Riches, we deploy autonomous AI systems like Jarvis 3.5 "
            f"to streamline operations and scale revenue.\n\n"
            f"Are you open to seeing how this could impact your business?\n"
            f"More info here: {conversion_link}\n\n"
            f"Best,\nRobert DeMotto Jr.\nRealms2Riches Operator"
        )

        if settings.SMTP_USER and settings.SMTP_PASS:
            try:
                import smtplib
                from email.mime.text import MIMEText
                
                msg = MIMEText(body)
                msg['Subject'] = subject
                msg['From'] = settings.SMTP_USER
                msg['To'] = target_email
                
                with smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT) as server:
                    server.starttls()
                    server.login(settings.SMTP_USER, settings.SMTP_PASS)
                    server.send_message(msg)
                
                return {
                    "status": "success", 
                    "action": "outreach_dispatched", 
                    "method": "email",
                    "target": target_email,
                    "conversion_link": conversion_link
                }
            except Exception as e:
                logger.error(f"Email outreach failed: {e}")
                return {"status": "error", "reason": f"SMTP Error: {str(e)}"}
        
        return {
            "status": "success", 
            "action": "outreach_simulated", 
            "reason": "SMTP not configured",
            "target": target_email,
            "draft_body": body,
            "conversion_link": conversion_link
        }

class SEOContentFactoryTool(BaseTool):
    """
    SEO / Organic Traffic Funnel.
    Generates mass technical content to attract Google Search traffic.
    """
    def execute(self, invocation: ToolInvocation) -> Dict[str, Any]:
        params = invocation.input_data
        topic, keywords = params.get("topic"), params.get("keywords", [])
        
        slug = f"technical-breakdown-{topic.lower().replace(' ', '-')}"
        path = f"data/blog/{slug}.md"
        
        # FIXED: Proper multiline f-string formatting
        content = f"# {topic}\nTechnical Authority generated by Sovereign SEO Factory.\n\nKeywords: {', '.join(keywords)}\n\n[🛒 SECURE PLATINUM LICENSE](https://buy.stripe.com/fZu9ATdSzcVM3459ezgYU06?locale=en)"
        
        try:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
            return {"status": "success", "blog_path": path, "slug": slug}
        except Exception as e:
            return {"status": "error", "reason": str(e)}

def get_multiplication_tools() -> List[BaseTool]:
    cfg = {"type": "object", "properties": {"target": {"type": "string"}, "platform": {"type": "string"}}}
    return [
        OutreachSwarmTool(ToolConfig(tool_id="outreach", name="Outreach", description="Cold Outreach Funnel", parameters_schema=cfg, allowed_agents=["*"])),
        SEOContentFactoryTool(ToolConfig(tool_id="seo_factory", name="SEO", description="Mass Organic Funnel", parameters_schema=cfg, allowed_agents=["*"]))
    ]
