export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto py-10">
      <h1 className="text-4xl font-bold mb-6">Terms of Service</h1>
      <p className="text-gray-400 mb-4">Effective Date: 2026-02-18</p>
      <div className="prose prose-invert">
        <p>By using Realms to Riches, you agree to these terms.</p>
        <h3>Usage License</h3>
        <p>You are granted a limited license to use our agentic platform for lawful software development purposes.</p>
        <h3>Liability</h3>
        <p>Realms to Riches is provided "as is". We are not liable for code generated by autonomous agents.</p>
      </div>
    </div>
  );
}
